version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install poetry
    - poetry install --with docs
    - poetry run sphinx-build -W -b html docs _readthedocs/html

sphinx:
  configuration: docs/conf.py